server:
  port: 8080
spring:
  application:
    name: test11_14
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_test?characterEncoding=utf8&useSSL=false
    username: root
    password: '219161'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true #配置驼峰自动转换
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志
  mapper-locations: classpath:mapper/**Mapper.xml
# 日志
logging:
  file:
    name: spring-book.log






#    sky:
#      datasource:

#        host: localhost
#        port: 3306
#        database: sky_take_out
#        username: root
#        password: '219161'
#        driver-class-name: com.mysql.cj.jdbc.Driver